version: '3.8'

services:
  python-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY:-}
    command: python python_service.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    working_dir: /app
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  go-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=${GIN_MODE:-release}
      - PYTHON_SERVICE_URL=http://python-service:8000
      - DB_PATH=/app/data/ytchat.db
    command: go run cmd/main.go
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./templates:/app/templates
    working_dir: /app
    depends_on:
      - python-service
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
  logs:
